name: Trigger build openwrt daily

on: 
  schedule:
    - cron: '0 16 * * *'  # Runs at 16:00 UTC (which is 12 AM GMT+8)

jobs:
  trigger-foo:
    runs-on: ubuntu-latest
    steps:
      - name: Build dlink_dir-882-a1
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-openwrt.yml',
              ref: 'master',
              inputs: {
                version: 'snapshot',
                profile: 'ramips/mt7621/dlink_dir-882-a1',
                package: 'luci'
              }
            })
      - name: Build dlink_dir-2150-a1
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-openwrt.yml',
              ref: 'master',
              inputs: {
                version: 'snapshot',
                profile: 'ramips/mt7621/dlink_dir-2150-a1',
                package: 'luci luci-app-sqm'
              }
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
